# Site settings
title: Topological Circuit Group
email:
description: > # this means to ignore newlines until "baseurl:"
  Build eletrical circuits based on topological quantum matter
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Alexandre Assouline
email: alexandre.assouline@neel.cnrs.fr
facebook_username:
twitter_username:
github_username: aassouline
address:
  - line: 25 av. des martyrs. 38000 Grenoble. France
  - line:
  # Feel free to add more lines here 
telephone: 
copyright:

# API settings
google_api_key: 

# Build settings
markdown: kramdown
